name: .NET Build & Test

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET 6.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "6.0.x"
      - name: Restore dependencies
        run: dotnet restore VietQRHelper.sln
      - name: Build
        run: dotnet build VietQRHelper.sln --configuration Release --no-restore
      - name: Run Console Test
        run: dotnet run --project VietQRConsoleTest/VietQRConsoleTest.csproj
